// src/app/models/student.model.ts
export interface Student {
  id: number;
  name: string;
  surName: string;
  rollNo: number;
  maktabClass?: MaktabClass | null;
  age: number;
  gender: 'Male' | 'Female';
  guardianName?: string;
  phone?: string;
  imagePath?: string;
  fees: Fee[];
  status: string;
  admissionDate: string;
  attendance: Attendance[];
  dateOfBirth?: string;
  fatherName?: string;
  surname?: string;
  whatsapp?: string;
  classId?: number;
  address?: string;
  schoolName?: string;
  parentProfession?: string;
}

// src/app/models/maktab-class.model.ts
export interface MaktabClass {
  studentCount: number;
  timing: string;
  division: string;
  id?: number;
  name: string;
  teacher?: Teacher[];
  subject?: Subject[];
  student?: Student[];
}

// src/app/models/teacher.model.ts
export interface Teacher {
  maktabClass: MaktabClass;
  id?: number;
  fullName: string;
  phone?: string;
}

// src/app/models/subject.model.ts
export interface Subject {
  id?: number;
  name: string;
  classes?: MaktabClass[];
  teacher?: Teacher[];
}

// src/app/models/attendance.model.ts
export interface Attendance {
  id: number;
  studentId: number;
  studentName: string;
  student: Student;
  className: string;
  attendanceDate: string; // YYYY-MM-DD
  attendanceStatus: 'PRESENT' | 'ABSENT';
  remark: string;
}

// src/app/models/fee.model.ts
export interface Fee {
  id: number;
  studentId: number;
  month: string;
  year: number;
  status: string;
  paymentDate: Date;
  dueDate: Date;
  paymentMode: string;
  recordedBy: string;
  remark: string;
  paidAmount: number;
}

export interface BatchFeeRequest {
  studentIds: number[];
  status: string;
}

export interface FeeResponse {
  studentId: number;
  feeId: number;
  status: string;
}

export interface BatchFeeResponse {
  createdFees: FeeResponse[];
  message: string;
}

export interface FeeDTO {
  id: number;
  month: string;
  year: number;
  status: string;
  paymentDate: Date;
  paymentMode: string;
  recordedBy: string;
  remark: string;
  paidAmount: number;
}

export interface StudentFeeDTO {
  studentName: string;
  studentClass: string;
  phone: string;
  admissionDate: string;
  fees: FeeDTO[];
}

export interface ManualData {
  id?: number;                // optional because it's generated by backend
  studentName: string;
  fatherName: string;
  surname: string;
  dob: string;                // can be Date if you want to parse it
  age: number;
  gender: string;
  address: string;
  mobileNo: string;
  residential: string;
  schoolName: string;
  parentsProfession: string;
  preferredTiming: string;
  admissionDate: string;
  teacherName: string;
  maktabClass: string;
  feesDetail: string;
  division: string;
  dataJson?: string;
}

export interface AttendanceSummary {
  total: number;
  attended: number;
  absent: number;
}

export interface ApplicationResponse {
  title: string;
  appName: string;
  version: string;
  description: string;
}

// src/app/models/teacher-salary.model.ts
export interface TeacherSalary {
  id?: number;
  teacher: Teacher;
  amount: number;
  salaryMonth: Date | string;
  paymentDate?: Date | string;
  isPaid: boolean;
  remarks?: string;
}

export interface AppNotification {
  message: string;
  type: 'success' | 'error' | 'info' | 'warning';
}
